
Public Class clsHospitalInfo
#Region "Variables"
    Dim operation, minfono, _
        mservicecapability, mr, mg, mb, mgovernment, mprivate, mqualitymanagement, mcommitteeid, mhospfacilityid, mreportseqno As Integer
    Private mHospName, mTradeName, mNoStreet, mBarangay, _
        mMunCity, mProvince, mregion, mZipCode, _
        mTelephone, mphilhealthaccredno, _
        mcategory, mphicaccreditedbeds, mdohauthorizedbeds, _
        mtaxacctno, mfaxno, memailaddress, mcatchmentpop, mmemo, _
         misspecial_specify, mgovernment_specify, _
      mqualitymanagement_specify, mqualitymanagementperiod, _
     mtotalbudget, mtotalincome, mexpenditure, mcommitteename, mcommittetype, mfacility, mremarks As String
    Private mvat, mtrackinventory, mishospnoautogenerated, _
        mishospnounique, misautopriceupdate, misstocktransferautoreceived, misgeneral_special, misexists As Boolean
    Private mEdate, mPDate, mHDate, mRDate, mSDate As DateTime




    Private mnew_icon _
      , medit_icon _
      , mcancel_icon _
      , mprint_icon _
      , msave_icon _
      , mclose_icon _
      , msearch_icon _
      , mselect_record_icon _
      , mcreate_new_record_icon _
      , minspect_icon _
      , mchecked_icon _
      , maccept_icon _
      , mrealease_icon _
      , mreceive_icon _
      , missue_icon _
      , mpost_icon _
      , mphilhealth_icon _
      , mcamera_icon _
      , mpencil_icon _
      , mfolder_picture_icon _
      , mload_item_icon _
      , mremove_icon _
      , mmale_icon _
      , mfemale_icon _
      , mextract_icon _
      , mcontinue_icon _
      , mview_icon, mlogo As Object



    Public eclaimsuserid As String
    Public eclaimspassword As String
    Public eclaimshospitalcode As String
    Public cipherkey As String
#End Region
#Region "Properties"
    Public Property committeeid() As Integer
        Get
            Return mcommitteeid
        End Get
        Set(ByVal value As Integer)
            mcommitteeid = value
        End Set
    End Property
    Public Property hospfacilityid() As Integer
        Get
            Return mhospfacilityid
        End Get
        Set(ByVal value As Integer)
            mhospfacilityid = value
        End Set
    End Property
    Public Property reportseqno() As Integer
        Get
            Return mreportseqno
        End Get
        Set(ByVal value As Integer)
            mreportseqno = value
        End Set
    End Property
    Public Property committeename() As String
        Get
            Return mcommitteename
        End Get
        Set(ByVal value As String)
            mcommitteename = value
        End Set
    End Property
    Public Property committetype() As String
        Get
            Return mcommittetype
        End Get
        Set(ByVal value As String)
            mcommittetype = value
        End Set
    End Property
    Public Property facility() As String
        Get
            Return mfacility
        End Get
        Set(ByVal value As String)
            mfacility = value
        End Set
    End Property
    Public Property remarks() As String
        Get
            Return mremarks
        End Get
        Set(ByVal value As String)
            mremarks = value
        End Set
    End Property
    Public Property isexists() As Boolean
        Get
            Return misexists
        End Get
        Set(ByVal value As Boolean)
            misexists = value
        End Set
    End Property

    Public Property isgeneral_special() As Boolean
        Get
            Return misgeneral_special
        End Get
        Set(ByVal value As Boolean)
            misgeneral_special = value
        End Set
    End Property
    Public Property isspecial_specify() As String
        Get
            Return misspecial_specify
        End Get
        Set(ByVal value As String)
            misspecial_specify = value
        End Set
    End Property
    Public Property government() As Integer
        Get
            Return mgovernment
        End Get
        Set(ByVal value As Integer)
            mgovernment = value
        End Set
    End Property
    Public Property government_specify() As String
        Get
            Return mgovernment_specify
        End Get
        Set(ByVal value As String)
            mgovernment_specify = value
        End Set
    End Property
    Public Property xprivate() As Integer
        Get
            Return mprivate
        End Get
        Set(ByVal value As Integer)
            mprivate = value
        End Set
    End Property
    Public Property qualitymanagement() As Integer
        Get
            Return mqualitymanagement
        End Get
        Set(ByVal value As Integer)
            mqualitymanagement = value
        End Set
    End Property
    Public Property qualitymanagement_specify() As String
        Get
            Return mqualitymanagement_specify
        End Get
        Set(ByVal value As String)
            mqualitymanagement_specify = value
        End Set
    End Property
    Public Property qualitymanagementperiod() As DateTime
        Get
            Return mqualitymanagementperiod
        End Get
        Set(ByVal value As DateTime)
            mqualitymanagementperiod = value
        End Set
    End Property
    Public Property totalbudget() As Double
        Get
            Return mtotalbudget
        End Get
        Set(ByVal value As Double)
            mtotalbudget = value
        End Set
    End Property
    Public Property totalincome() As Double
        Get
            Return mtotalincome
        End Get
        Set(ByVal value As Double)
            mtotalincome = value
        End Set
    End Property
    Public Property expenditure() As Double
        Get
            Return mexpenditure
        End Get
        Set(ByVal value As Double)
            mexpenditure = value
        End Set
    End Property


    Public Property EDate() As DateTime
        Get
            Return mEdate
        End Get
        Set(ByVal value As DateTime)
            mEdate = value
        End Set
    End Property
    Public Property PDate() As DateTime
        Get
            Return mPDate
        End Get
        Set(ByVal value As DateTime)
            mPDate = value
        End Set
    End Property
    Public Property HDate() As DateTime
        Get
            Return mHDate
        End Get
        Set(ByVal value As DateTime)
            mHDate = value
        End Set
    End Property
    Public Property RDate() As DateTime
        Get
            Return mRDate
        End Get
        Set(ByVal value As DateTime)
            mRDate = value
        End Set
    End Property
    Public Property SDate() As DateTime
        Get
            Return mSDate
        End Get
        Set(ByVal value As DateTime)
            mSDate = value
        End Set
    End Property




    Public Property infono() As Integer
        Get
            Return minfono
        End Get
        Set(ByVal value As Integer)
            minfono = value
        End Set
    End Property
    Public Property HospName() As String
        Get
            Return mHospName
        End Get
        Set(ByVal value As String)
            mHospName = value
        End Set
    End Property
    Public Property TradeName() As String
        Get
            Return mTradeName
        End Get
        Set(ByVal value As String)
            mTradeName = value
        End Set
    End Property
    Public Property NoStreet() As String
        Get
            Return mNoStreet
        End Get
        Set(ByVal value As String)
            mNoStreet = value
        End Set
    End Property
    Public Property Barangay() As String
        Get
            Return mBarangay
        End Get
        Set(ByVal value As String)
            mBarangay = value
        End Set
    End Property
    Public Property MunCity() As String
        Get
            Return mMunCity
        End Get
        Set(ByVal value As String)
            mMunCity = value
        End Set
    End Property

    Public Property Province() As String
        Get
            Return mProvince
        End Get
        Set(ByVal value As String)
            mProvince = value
        End Set
    End Property
    Public Property region() As String
        Get
            Return mregion
        End Get
        Set(ByVal value As String)
            mregion = value
        End Set
    End Property
    Public Property ZipCode() As String
        Get
            Return mZipCode
        End Get
        Set(ByVal value As String)
            mZipCode = value
        End Set
    End Property
    Public Property Telephone() As String
        Get
            Return mTelephone
        End Get
        Set(ByVal value As String)
            mTelephone = value
        End Set
    End Property
    Public Property philhealthaccredno() As String
        Get
            Return mphilhealthaccredno
        End Get
        Set(ByVal value As String)
            mphilhealthaccredno = value
        End Set
    End Property
    Public Property category() As String
        Get
            Return mcategory
        End Get
        Set(ByVal value As String)
            mcategory = value
        End Set
    End Property
    Public Property phicaccreditedbeds() As Integer
        Get
            Return mphicaccreditedbeds
        End Get
        Set(ByVal value As Integer)
            mphicaccreditedbeds = value
        End Set
    End Property
    Public Property dohauthorizedbeds() As Integer
        Get
            Return mdohauthorizedbeds
        End Get
        Set(ByVal value As Integer)
            mdohauthorizedbeds = value
        End Set
    End Property
    Public Property logo() As Object
        Get
            Return mlogo
        End Get
        Set(ByVal value As Object)
            mlogo = value
        End Set
    End Property

    Public Property vat() As Boolean
        Get
            Return mvat
        End Get
        Set(ByVal value As Boolean)
            mvat = value
        End Set
    End Property
    Public Property taxacctno() As String
        Get
            Return mtaxacctno
        End Get
        Set(ByVal value As String)
            mtaxacctno = value
        End Set
    End Property
    Public Property faxno() As String
        Get
            Return mfaxno
        End Get
        Set(ByVal value As String)
            mfaxno = value
        End Set
    End Property
    Public Property emailaddress() As String
        Get
            Return memailaddress
        End Get
        Set(ByVal value As String)
            memailaddress = value
        End Set
    End Property
    Public Property catchmentpop() As String
        Get
            Return mcatchmentpop
        End Get
        Set(ByVal value As String)
            mcatchmentpop = value
        End Set
    End Property
    Public Property servicecapability() As Integer
        Get
            Return mservicecapability
        End Get
        Set(ByVal value As Integer)
            mservicecapability = value
        End Set
    End Property
    Public Property trackinventory() As Boolean
        Get
            Return mtrackinventory
        End Get
        Set(ByVal value As Boolean)
            mtrackinventory = value
        End Set
    End Property

    Public Property ishospnoautogenerated() As Boolean
        Get
            Return mishospnoautogenerated
        End Get
        Set(ByVal value As Boolean)
            mishospnoautogenerated = value
        End Set
    End Property
    Public Property ishospnounique() As Boolean
        Get
            Return mishospnounique
        End Get
        Set(ByVal value As Boolean)
            mishospnounique = value
        End Set
    End Property
    Public Property isautopriceupdate() As Boolean
        Get
            Return misautopriceupdate
        End Get
        Set(ByVal value As Boolean)
            misautopriceupdate = value
        End Set
    End Property
    Public Property isstocktransferautoreceived() As Boolean
        Get
            Return misstocktransferautoreceived
        End Get
        Set(ByVal value As Boolean)
            misstocktransferautoreceived = value
        End Set
    End Property

    Public Property new_icon() As Object
        Get
            Return mnew_icon
        End Get
        Set(ByVal value As Object)
            mnew_icon = value
        End Set
    End Property
    Public Property edit_icon() As Object
        Get
            Return medit_icon
        End Get
        Set(ByVal value As Object)
            medit_icon = value
        End Set
    End Property
    Public Property cancel_icon() As Object
        Get
            Return mcancel_icon
        End Get
        Set(ByVal value As Object)
            mcancel_icon = value
        End Set
    End Property
    Public Property print_icon() As Object
        Get
            Return mprint_icon
        End Get
        Set(ByVal value As Object)
            mprint_icon = value
        End Set
    End Property
    Public Property save_icon() As Object
        Get
            Return msave_icon
        End Get
        Set(ByVal value As Object)
            msave_icon = value
        End Set
    End Property
    Public Property close_icon() As Object
        Get
            Return mclose_icon
        End Get
        Set(ByVal value As Object)
            mclose_icon = value
        End Set
    End Property
    Public Property search_icon() As Object
        Get
            Return msearch_icon
        End Get
        Set(ByVal value As Object)
            msearch_icon = value
        End Set
    End Property
    Public Property select_record_icon() As Object
        Get
            Return mselect_record_icon
        End Get
        Set(ByVal value As Object)
            mselect_record_icon = value
        End Set
    End Property
    Public Property create_new_record_icon() As Object
        Get
            Return mcreate_new_record_icon
        End Get
        Set(ByVal value As Object)
            mcreate_new_record_icon = value
        End Set
    End Property
    Public Property inspect_icon() As Object
        Get
            Return minspect_icon
        End Get
        Set(ByVal value As Object)
            minspect_icon = value
        End Set
    End Property
    Public Property checked_icon() As Object
        Get
            Return mchecked_icon
        End Get
        Set(ByVal value As Object)
            mchecked_icon = value
        End Set
    End Property
    Public Property accept_icon() As Object
        Get
            Return maccept_icon
        End Get
        Set(ByVal value As Object)
            maccept_icon = value
        End Set
    End Property
    Public Property realease_icon() As Object
        Get
            Return mrealease_icon
        End Get
        Set(ByVal value As Object)
            mrealease_icon = value
        End Set
    End Property
    Public Property receive_icon() As Object
        Get
            Return mreceive_icon
        End Get
        Set(ByVal value As Object)
            mreceive_icon = value
        End Set
    End Property
    Public Property issue_icon() As Object
        Get
            Return missue_icon
        End Get
        Set(ByVal value As Object)
            missue_icon = value
        End Set
    End Property
    Public Property post_icon() As Object
        Get
            Return mpost_icon
        End Get
        Set(ByVal value As Object)
            mpost_icon = value
        End Set
    End Property

    Public Property philhealth_icon() As Object
        Get
            Return mphilhealth_icon
        End Get
        Set(ByVal value As Object)
            mphilhealth_icon = value
        End Set
    End Property
    Public Property camera_icon() As Object
        Get
            Return mcamera_icon
        End Get
        Set(ByVal value As Object)
            mcamera_icon = value
        End Set
    End Property
    Public Property pencil_icon() As Object
        Get
            Return mpencil_icon
        End Get
        Set(ByVal value As Object)
            mpencil_icon = value
        End Set
    End Property
    Public Property folder_picture_icon() As Object
        Get
            Return mfolder_picture_icon
        End Get
        Set(ByVal value As Object)
            mfolder_picture_icon = value
        End Set
    End Property
    Public Property load_item_icon() As Object
        Get
            Return mload_item_icon
        End Get
        Set(ByVal value As Object)
            mload_item_icon = value
        End Set
    End Property
    Public Property remove_icon() As Object
        Get
            Return mremove_icon
        End Get
        Set(ByVal value As Object)
            mremove_icon = value
        End Set
    End Property
    Public Property male_icon() As Object
        Get
            Return mmale_icon
        End Get
        Set(ByVal value As Object)
            mmale_icon = value
        End Set
    End Property
    Public Property female_icon() As Object
        Get
            Return mfemale_icon
        End Get
        Set(ByVal value As Object)
            mfemale_icon = value
        End Set
    End Property
    Public Property extract_icon() As Object
        Get
            Return mextract_icon
        End Get
        Set(ByVal value As Object)
            mextract_icon = value
        End Set
    End Property
    Public Property continue_icon() As Object
        Get
            Return mcontinue_icon
        End Get
        Set(ByVal value As Object)
            mcontinue_icon = value
        End Set
    End Property
    Public Property view_icon() As Object
        Get
            Return mview_icon
        End Get
        Set(ByVal value As Object)
            mview_icon = value
        End Set
    End Property

    Public Property r() As Integer
        Get
            Return mr
        End Get
        Set(ByVal value As Integer)
            mr = value
        End Set
    End Property
    Public Property g() As Integer
        Get
            Return mg
        End Get
        Set(ByVal value As Integer)
            mg = value
        End Set
    End Property
    Public Property b() As Integer
        Get
            Return mb
        End Get
        Set(ByVal value As Integer)
            mb = value
        End Set
    End Property
    Public Property memo() As String
        Get
            Return mmemo
        End Get
        Set(ByVal value As String)
            mmemo = value
        End Set
    End Property
#End Region
#Region "Methods"
    Public Shared Function getInfo(ByVal soperation As Integer, Optional ByVal search As String = "") As DataTable
        Dim strPar() As String = {"@operation", "@soperation", "@search"}
        Dim strVal() As String = {0, soperation, search}
        'Return GenericDA.ManageQuery(strPar, strVal, "sphospitalinformation", 0)
        Dim s As New simpleadapter.SimpleAdapter(gconnectionstring)
        Return s.SetParam(strPar, strVal, "sphospitalinformation", 0)
    End Function
    Public Sub saveInfo(ByVal isNew As Boolean, ByVal hasremove As Integer, Optional ByVal soperation As Integer = 0)
        If isNew Then
            operation = 1
        Else
            operation = 2
        End If
        Dim strPar() As String = {"@operation", _
                                  "@soperation", _
                                  "@infono", _
                                  "@HospName", _
                                  "@TradeName", _
                                  "@NoStreet", _
                                  "@Barangay", _
                                  "@MunCity", _
                                  "@Province", _
                                  "@region", _
                                  "@ZipCode", _
                                  "@Telephone", _
                                  "@philhealthaccredno", _
                                  "@category", _
                                  "@phicaccreditedbeds", _
                                  "@dohauthorizedbeds", _
                                  "@hospitallogo", _
                                  "@hasremove", _
                                  "@vat", _
                                  "@taxacctno", _
                                  "@faxno", _
                                  "@emailaddress", _
                                  "@catchmentpop", _
                                  "@servicecapability", _
                                  "@trackinventory", _
                                  "@ishospnoautogenerated", _
                                  "@ishospnounique", _
                                  "@isautopriceupdate", _
                                  "@isstocktransferautoreceived", _
                                  "@new_icon", _
      "@edit_icon", _
      "@cancel_icon", _
      "@print_icon", _
      "@save_icon", _
      "@close_icon", _
      "@search_icon", _
      "@select_record_icon", _
      "@create_new_record_icon", _
      "@inspect_icon", _
      "@checked_icon", _
      "@accept_icon", _
      "@realease_icon", _
      "@receive_icon", _
      "@issue_icon", _
      "@post_icon", _
      "@r", _
         "@g", _
            "@b", _
                "@philhealth_icon", _
      "@camera_icon", _
      "@pencil_icon", _
      "@folder_picture_icon", _
      "@load_item_icon", _
      "@remove_icon", _
      "@male_icon", _
      "@female_icon", _
      "@extract_icon", _
      "@continue_icon", _
      "@view_icon", "@h_memo", "@createdbyid", _
                                  "@updatedbyid", _
                                  "@empARCutOffDate", _
                                  "@ptARCutOffDate", _
                                  "@hmoARCutOffDate", _
                                  "@rgARCutOffDate", _
                                  "@supAPCutOffDate", _
                                  "@isgeneral_special", _
     "@isspecial_specify", _
     "@government", _
     "@government_specify", _
     "@private", _
     "@qualitymanagement", _
     "@qualitymanagement_specify", _
     "@qualitymanagementperiod", _
     "@totalbudget", _
     "@totalincome", _
     "@expenditure", _
                      "committeeid", _
     "committeename", _
     "committetype", _
     "isexists", _
     "reportseqno", _
     "remarks", _
     "hospfacilityid", _
     "facility"}
        Dim strVal() As Object = {Me.operation, _
                                  soperation, _
                                  Me.infono, _
                                  Me.HospName, _
                                  Me.TradeName, _
                                  Me.NoStreet, _
                                  Me.Barangay, _
                                  Me.MunCity, _
                                  Me.Province, _
                                  Me.region, _
                                  Me.ZipCode, _
                                  Me.Telephone, _
                                  Me.philhealthaccredno, _
                                  Me.category, _
                                  Me.phicaccreditedbeds, _
                                  Me.dohauthorizedbeds, _
                                  Me.logo, _
                                  hasremove, _
                                  Me.vat, _
                                  Me.taxacctno, _
                                  Me.faxno, _
                                  Me.emailaddress, _
                                  Me.catchmentpop, _
                                  Me.servicecapability, _
                                  Me.trackinventory, _
                                  Me.ishospnoautogenerated, _
                                  Me.ishospnounique, _
                                  Me.isautopriceupdate, _
                                  Me.isstocktransferautoreceived, _
      Me.new_icon, _
      Me.edit_icon, _
      Me.cancel_icon, _
      Me.print_icon, _
      Me.save_icon, _
      Me.close_icon, _
      Me.search_icon, _
      Me.select_record_icon, _
      Me.create_new_record_icon, _
      Me.inspect_icon, _
      Me.checked_icon, _
      Me.accept_icon, _
      Me.realease_icon, _
      Me.receive_icon, _
      Me.issue_icon, _
      Me.post_icon, _
      Me.r, _
      Me.g, _
      Me.b, _
             Me.philhealth_icon, _
       Me.camera_icon, _
       Me.pencil_icon, _
       Me.folder_picture_icon, _
       Me.load_item_icon, _
       Me.remove_icon, _
       Me.male_icon, _
       Me.female_icon, _
       Me.extract_icon, _
       Me.continue_icon, _
       Me.view_icon, Me.memo, modGlobal.employeeid, modGlobal.employeeid, Me.EDate, Me.PDate, Me.HDate, Me.RDate, Me.mSDate, _
                                  Me.isgeneral_special, _
     Me.isspecial_specify, _
     Me.government, _
     Me.government_specify, _
     Me.xprivate, _
     Me.qualitymanagement, _
     Me.qualitymanagement_specify, _
     Me.qualitymanagementperiod, _
     Me.totalbudget, _
     Me.totalincome, _
     Me.expenditure, _
         Me.committeeid, _
        Me.committeename, _
        Me.committetype, _
        Me.isexists, _
        Me.reportseqno, _
        Me.remarks, _
        Me.hospfacilityid, _
        Me.facility}
        'Return GenericDA.ManageQuery(strPar, strVal, "sphospitalinformation", 1)
        Dim s As New simpleadapter.SimpleAdapter(gconnectionstring)
        s.SetParam(strPar, strVal, "sphospitalinformation", 1)
    End Sub

    Public Sub savePhoto()
        Dim strPar() As String = {"@operation", "@soperation", "hospitallogo"}
        Dim strVal() As Object = {2, 2, logo}
        Dim s As New simpleadapter.SimpleAdapter(gconnectionstring)
        s.SetParam(strPar, strVal, "sphospitalinformation", 1)
    End Sub
    Public Sub saveBasicInfo()
        Dim strPar() As String = {"@operation", "@soperation", "HospName", "NoStreet", "Barangay", "MunCity", "Province", "region", "Telephone"}
        Dim strVal() As String = {2, 3, HospName, mNoStreet, mBarangay, mMunCity, mProvince, mregion, Telephone}
        Dim s As New simpleadapter.SimpleAdapter(gconnectionstring)
        s.SetParam(strPar, strVal, "sphospitalinformation", 1)
    End Sub

    Public Sub savePhilhealthCredentials()
        Dim strPar() As String = {"operation", "soperation", "eclaimsuserid", "eclaimspassword", "eclaimshospitalcode", "cipherkey"}
        Dim strVal() As Object = {2, 5, eclaimsuserid, eclaimspassword, eclaimshospitalcode, cipherkey}
        Dim s As New simpleadapter.SimpleAdapter(gconnectionstring)
        s.SetParam(strPar, strVal, "sphospitalinformation", 1)
    End Sub
#End Region
End Class
